[package]
name = "ilkil/trials"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"
matter = "matter-ecs/matter@0.8.4"
